FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]

# to build using dev file, run 'docker build -f Dockerfile.dev .'
# since by default it will look for just 'Dockerfile'