version: "3"
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # need this part for volumes since im on windows
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # recall that docker volumes make it so that the changes we make
      # to index on save are reflected immediately in the container
      - /app/node_modules
      - .:/app
  tests: # This container is responsible for running tests
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
